{{- if .Values.notification.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}-notification
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: notification
spec:
  type: {{ .Values.notification.service.type }}
  ports:
    - name: http
      port: {{ .Values.notification.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "todo-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: notification
{{- end }}
