{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-app.frontend.fullname" . }}-config
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    {{- include "todo-app.frontend.selectorLabels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.frontend.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}

---

{{- if .Values.backend.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-app.backend.fullname" . }}-config
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    {{- include "todo-app.backend.selectorLabels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.backend.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
